spring:
  application:
    name: recommendation-expert
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4-turbo
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE

sfg:
  aiapp:
    vectorStorePath: /tmp/vector-store.json
    documentsToLoad:
      - classpath:/cv.json
      # list of vacancies
      - https://www.epam.com/careers/job-listings?country=all&relocation=true&remote=true